name: Deploy
on: [pull_request, push]
env:
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]  # windows-latest, macOS-latest
        node: [16.x, 18.x]
    name: Test with Node ${{ matrix.node }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g typescript rollup
      - run: npm ci
      - run: npm test
  deploy:
    name: Deploy Docs, Packages
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: git clone https://${GITHUB_TOKEN}@github.com/nodef/deploy "$HOME/deploy"
      - run: chmod 777 "$HOME/deploy/"*.sh
      - run: bash "$HOME/deploy/before_install.sh"
      - run: npm i -g typescript rollup typedoc browserify terser
      - run: bash "$HOME/deploy/script.sh"
